# lidar_driver:
/**:
  ros__parameters:
    scan_topic: "/scan"
    imu_topic: "/imu" 
    driver_period: 0.005
    lidar_freq: 20.0
    range_min: 0.01
    range_max: 45.0
    hostname: "192.168.0.200"
    scan_port: 2115
    imu_port: 7503
    frame: "lidar_sensor"
