# dyn_driver:
/**:
  ros__parameters:
    command_topic: "/dyn_command_int"
    read_topic: "/dyn_read_int" 
    driver_read_period: 0.1
    port: "/dev/ttyUSB0"
    id_list: [1,2]
    motor_gains: [600,50,20]
